// ABOUTME: Generates HTML email content from bookmarked tweets.
// ABOUTME: Groups bookmarks by folder and renders author/tweet info. Shared by CLI and web.

import type { StoredBookmark } from "./types";
import { escapeHtml } from "./html";
import { tweetUrl } from "./urls";

function formatDate(dateStr: string | null): string {
  if (!dateStr) return "";
  const d = new Date(dateStr);
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

export function renderNewsletter(bookmarks: StoredBookmark[]): { html: string; subject: string } {
  const date = new Date().toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
  const subject = `Your X Bookmarks — ${date}`;

  if (bookmarks.length === 0) {
    return {
      subject,
      html: wrapHtml(subject, "<p>No new bookmarks this week.</p>"),
    };
  }

  // Group by folder
  const grouped = new Map<string, StoredBookmark[]>();
  for (const bm of bookmarks) {
    const key = bm.folder_name || "Unsorted";
    const list = grouped.get(key) || [];
    list.push(bm);
    grouped.set(key, list);
  }

  let body = "";
  for (const [folder, items] of grouped) {
    body += `<h2 style="color:#1d9bf0;margin:24px 0 12px;">${escapeHtml(folder)} (${items.length})</h2>\n`;
    for (const bm of items) {
      const url = tweetUrl(bm.tweet_id, bm.author_username);
      const author = bm.author_name
        ? `${escapeHtml(bm.author_name)} (@${escapeHtml(bm.author_username || "")})`
        : "Unknown author";
      const dateStr = formatDate(bm.created_at);

      body += `
        <div style="border:1px solid #e1e8ed;border-radius:12px;padding:16px;margin:8px 0;background:#fff;">
          <div style="font-weight:600;margin-bottom:4px;">${author}</div>
          <div style="margin-bottom:8px;">${escapeHtml(bm.text)}</div>
          <div style="font-size:13px;color:#657786;">
            ${dateStr ? `${dateStr} · ` : ""}<a href="${escapeHtml(url)}" style="color:#1d9bf0;">View on X</a>
          </div>
        </div>
      `;
    }
  }

  return { subject, html: wrapHtml(subject, body) };
}

function wrapHtml(title: string, body: string): string {
  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>${escapeHtml(title)}</title></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:600px;margin:0 auto;padding:20px;background:#f5f8fa;color:#14171a;">
  <h1 style="font-size:22px;margin-bottom:4px;">${escapeHtml(title)}</h1>
  ${body}
  <hr style="border:none;border-top:1px solid #e1e8ed;margin:24px 0;">
  <p style="font-size:12px;color:#657786;">Generated by xbook</p>
</body>
</html>`;
}
